#!/bin/sh 

stty -F /dev/ttyS1 speed 115200 cs8 -cstopb -parenb
echo "B001g" > /dev/ttyS1

if grep -qE '\s?psplash=false\s?' /proc/cmdline; then
	echo "Boot splashscreen disabled"
	exit 0;
fi

echo 140 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio140/direction
echo 1 > /sys/class/gpio/gpio140/value

. /etc/init.d/functions
. /etc/default/psplash

case `machine_id` in
    "hp_ipaq_h3100"|"hp_ipaq_h3800") 
	PARAMS='-a 90' ;;
    "hp_ipaq_3600"|"hp_ipaq_3700"|"hp_ipaq_h3900"|"htc_universal"|*collie|*poodle|*akita|*spitz|*borzoi)
	PARAMS='-a 270' ;;
esac

export TMPDIR=/mnt/.splash
mount tmpfs -t tmpfs $TMPDIR -o,size=40k

/usr/bin/psplash $PARAMS &

# Timetrap against hanging with splash hiding console messages.
#(sleep 120; psplash-write "QUIT") &
